__author__ = 'kostas'

import imp
import os

from cvl.framework.query import WILDCARD
from cvl.engines.postgres.sql import *
from cvl.util.anonobject import Object


class CodeGenerator(object):
    """docstring for Transaction"""

    def __init__(self, query, solver_name, **options):
        super(CodeGenerator, self).__init__()
        self.query = query
        self._load_solver(solver_name)
        self._load_constraints()
        self.options = options
        self.code = []

    def set_query(self, query):
        self.query = query

    def _get_formatter(self, **kwargs):
        formatter = self.query.__dict__.copy()
        for key, value in kwargs.items():
            formatter[key] = value
        return formatter

    def _load_module(self, module, submodule):
        root = os.path.dirname(os.path.realpath(__file__))
        module_file = os.path.join(root, module, '{0:s}.py'.format(submodule))
        module_name = 'cvl.engines.postgres.{module}.{submodule}'.format(module=module, submodule=submodule)
        return imp.load_source(module_name, module_file)

    def _load_solver(self, solver_name):
        module = self._load_module('solvers', solver_name)
        self.SOLVER = module.SOLVER

    def _load_constraints(self):
        self.constraints = []
        for constraint in self.query.subject_to:
            module = self._load_module('constraints', constraint.name)
            self.constraints.append(Object(
                name=constraint.name,
                params=constraint.params,
                SET_UP=module.SET_UP,
                FIND_CONFLICTS=module.FIND_CONFLICTS,
                CLEAN_UP=module.CLEAN_UP)
            )

    def Info(self, *info):
        for comment in info:
            self.code.append(COMMENT.format(comment=comment))

    def Initialize(self):
        formatter = self._get_formatter()
        self.Info("-"*42,
                  "Code generated by CVL compiler",
                  "-"*42,
                  "Input:        {input}".format(**formatter),
                  "Output:       {output}".format(**formatter),
                  "Zoom-levels:  {zoomlevels}".format(**formatter),
                  "Partition by: {partition_by}".format(**formatter),
                  "Rank by:      {rank_by}".format(**formatter),
                  "-"*42)

        self.code.append(BEGIN_TX)

        self.Info('Dropping old version of output table')
        self.code.append(DROP_OUTPUT_TABLE.format(**formatter))

        self.Info('Creating new output table and index')
        self.code.append(CREATE_OUTPUT_TABLE_AND_INDEX.format(**formatter))

        self.Info('Adding CVL framework')
        self.code.append(ADD_FRAMEWORK)

    def Finalize(self):
        formatter = self._get_formatter()
        self.Info('Removing CVL framework')
        self.code.append(REMOVE_FRAMEWORK)
        self.code.append(COMMIT_TX)
        self.Info('Try this!')
        self.code.append(TRYTHIS.format(**formatter))

    def MergePartitions(self):
        formatter = self._get_formatter()
        code = []
        merged = []
        self.Info('Merging partitions')
        for merge_clause in filter(lambda clause: clause.before is not WILDCARD, self.query.merge_partitions):
            formatter['before_merge'] = ', '.join(map(lambda m: "'{0:s}'".format(m), merge_clause.before))
            formatter['after_merge'] = merge_clause.after
            code.append(MERGE_PARTITIONS.format(**formatter))
            merged.append(merge_clause.after)

        for merge_clause in filter(lambda clause: clause.before is WILDCARD, self.query.merge_partitions):
            formatter['merged'] = ', '.join(map(lambda m: "'{0:s}'".format(m), merged))
            formatter['after_merge'] = merge_clause.after
            code.append(MERGE_PARTITIONS_REST.format(**formatter))

        self.code.extend(code)

    def InitializeLevel(self, z, copy_from=None):
        formatter = self._get_formatter(z=z)
        self.Info('Initialization for level {0:d}'.format(z))
        if copy_from is not None:
            formatter['copy_from'] = copy_from
            self.Info('Copy data from level {0:d} to level {1:d}'.format(copy_from, z))
            self.code.append(COPY_LEVEL.format(**formatter))
        self.code.append(CREATE_TEMP_TABLES_FOR_LEVEL.format(**formatter))

    def ForceLevel(self, z):
        formatter = self._get_formatter(z=z)
        for force_clause in filter(lambda clause: clause.min_level == z + 1, self.query.force_level):
            self.Info('Force delete records')
            formatter['delete_partition'] = "'%s'" % force_clause.partition
            self.code.append(FORCE_LEVEL.format(**formatter))

    def FindConflicts(self, z):
        ignored_partitions = ', '.join(map(lambda x: ("'{0:s}'".format(x.partition)), self.query.force_level))
        formatter = self._get_formatter(
            z=z,
            ignored_partitions=ignored_partitions)
        self.Info('Find conflicts')
        has_ignored = ignored_partitions != ''
        for constraint in self.constraints:
            self.code.append(constraint.SET_UP.format(**formatter))
            for i, param in enumerate(constraint.params, start=1):
                formatter['parameter_{0:d}'.format(i)] = param
            formatter['constraint_select'] = constraint.FIND_CONFLICTS.format(**formatter)
            if has_ignored:
                self.code.append(FIND_CONFLICTS.format(**formatter))
            else:
                self.code.append(FIND_CONFLICTS_IGNORE.format(**formatter))
            self.code.append(constraint.CLEAN_UP.format(**formatter))

    def ResolveConflicts(self, z):
        formatter = self._get_formatter(z=z)
        formatter['solution'] = self.SOLVER.format(**formatter)
        self.Info('Insert records to delete in temp table')
        self.code.append(COLLECT_DELETIONS.format(**formatter))
        self.Info('Delete records')
        self.code.append(DO_DELETIONS.format(**formatter))

    def TransformLevel(self, z):
        formatter = self._get_formatter(z=z)
        if 'allornothing' in self.query.transform_by:
            self.Info('Apply all-or-nothing')
            self.code.append(ALLORNOTHING.format(**formatter))
        if 'simplify' in self.query.transform_by:
            self.Info('Simplifying level')
            self.code.append(SIMPLIFY.format(**formatter))

    def FinalizeLevel(self, z):
        formatter = self._get_formatter(z=z)
        self.Info('Clean-up for level %d' % z)
        self.code.append(DROP_TEMP_TABLES_FOR_LEVEL.format(**formatter))

    def SimplifyAll(self):
        formatter = self._get_formatter()
        self.Info('Simplifying output')
        if 'simplify_once' in self.query.transform_by:
            self.code.append(SIMPLIFY_ALL.format(**formatter))

    def TryThis(self):
        formatter = self._get_formatter()
        self.Comment('Something you can try')
        self.code.append(TRYTHIS.format(**formatter))

    def get_code(self):
        return "\n".join(self.code)
